### ISSUE TITLE
Fix OPAL link

### ISSUE THREAD

**Issue by jaens** [agraef/pure-lang#10]
Wiki is not editable, OPAL link under "Rewriting" page can be updated to http://projects.uebb.tu-berlin.de/opal/trac/

**Comment by agraef** [comment]
That link doesn't seem to work either. Has the page moved again?

**Comment by jaens** [comment]
Looks like it's down now.
I guess https://web.archive.org/web/20160527221023/http://projects.uebb.tu-berlin.de/opal/trac/ is it then, Google did not find any alternatives.

**Comment by agraef** [comment]
Should be fixed now, thanks.
