### ISSUE TITLE
The printed output of exp(1e-15) does not correspond to the actual value

### ISSUE THREAD

**Issue by mardukbp** [agraef/pure-lang#25]
I did the following experiments in the CLI (version 0.68 running on Linux):

```
> using math;
> exp(1e-14);
1.00000000000001
> exp(1e-15);
1.0
> exp(1e-15) - 1;
1.11022302462516e-15
> 1.000000000000001-1;
1.11022302462516e-15
> exp(1e-16) - 1;
0.0
```

As can be seen, exp(1e-15) prints 1.0, but in reality the value returned is 1.000000000000001. This is important because 1.0 means that the argument of the exponential is less than or equal to the machine epsilon. The rounding results from using floating-point arithmetic with 64 bits. The spurious rounding shown above is misleading.

**Comment by agraef** [comment]
Revisiting an old ticket, sorry for the delay. Pure uses the standard C library routines (sprintf, IIRC) for formatting doubles. Maybe the formats could be improved, but I'm not sure how. If anyone can advice, please do. Alternatively, Pure's mpfr module might be able to give better accuracy in printouts.
