### ISSUE TITLE
Inline code (invalid value)

### ISSUE THREAD

**Issue by nilqed** [agraef/pure-lang#28]
Inline (C) code does not work anymore?? (Ubuntu/Cygwin/MinGW):

> using inline;
inline.pure, line 1: inline.pure0.WGHnU9.bc: Invalid value

:: Example

	kfp@euler:~/devel$ pure -i
	
	 __ \  |   |  __| _ \    Pure 0.68 (x86_64-pc-linux-gnu)
	 |   | |   | |    __/    Copyright (c) 2008-2018 by Albert Graef
	 .__/ \__,_|_|  \___|    (Type 'help' for help, 'help copying'
	_|                       for license information.)
	
	Loaded prelude from /usr/lib/pure/prelude.pure.
	
	> using inline;
	inline.pure, line 1: inline.pure0.QmBufv.bc: Invalid value
	> 
	> clang --version
	> quit
	kfp@euler:~/devel$ clang --version
	clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
	Target: x86_64-pc-linux-gnu
	Thread model: posix
	InstalledDir: /usr/bin
	kfp@euler:~/devel$ 
	
	kfp@euler:~/devel$ cat inline.pure
	%<
	int mygcd(int x, int y)
	{
	  if (y == 0)
	    return x;
	  else
	    return mygcd(y, x%y);
	}
	%>	
	
	Same on cygwin and MinGW:
	
	kfp@NUC /cygdrive/c/Users/kfp/Desktop/work/pure
	$ clang --version
	clang version 5.0.1 (tags/RELEASE_501/final)
	Target: x86_64-unknown-windows-cygnus
	Thread model: posix
	InstalledDir: /usr/bin
	
	kfp@NUC MINGW32 /c/Users/kfp/Desktop
	$ clang --version
	clang version 3.8.0 (/repo/sources/clang 1d5b05f1ef9d1b9889ddb5ad946944f224a7ba88) (/repo/sources/llvm 2aebced35905eb3891eba484e4d1902cf7399558)
	Target: x86_64-pc-msys
	Thread model: posix
	InstalledDir: /usr/bin

**Comment by agraef** [comment]
You need clang 3.5. clang 6.0 will generate LLVM bitcode using LLVM 6.0 which is incompatible with LLVM 3.5, the version that Pure is still stuck with. Same goes for any clang x with x > 3.5.

**Comment by nilqed** [comment]
Thank you, this explains (the non-uniform versioning scheme can be misleading: Xcode clang up to 6.0.1  means LLVM <= 3.5, whereas 6.4/7.0/7.3 correspond to LLVM 3.6/3.7/3.8 respectively, hmm ;)
