### ISSUE TITLE
pure-mode for emacs?

### ISSUE THREAD

**Issue by unhandyandy** [agraef/pure-lang#29]
Pure-mode for emacs is no longer available on marmalade or melpa.  Maybe you could host it here?

**Comment by agraef** [comment]
I don't think it ever was.

pure-mode.el and .elc will be built and installed when you compile the pure package from source and an Emacs installation was detected, cf. https://agraef.github.io/pure-docs/install.html#emacs-pure-mode. It's also included in the Windows installer and MacPorts, and there's a separate package for Aquamacs on the Mac (see the corresponding Wiki pages, https://github.com/agraef/pure-lang/wiki/PureOnWindows#pure-and-emacs and https://github.com/agraef/pure-lang/wiki/PureOnMacOSX#pure-and-aquamacs).

**Comment by unhandyandy** [comment]
Ah, thanks.
