### ISSUE TITLE
Problem installing LV2 package

### ISSUE THREAD

**Issue by interstar** [agraef/pure-lang#31]
I'm trying to follow the instructions on  https://agraef.github.io/pure-docs/pure-lv2.html

To install the library for building LV2 plugins.

But I'm getting this error :

```Package pure was not found in the pkg-config search path.
Perhaps you should add the directory containing `pure.pc' to the PKG_CONFIG_PATH environment variable
No package 'pure' found`

```
repeated several times.

The archive at https://bitbucket.org/purelang/pure-lang/downloads/pure-lv2-0.2.tar.gz doesn't seemt to contain a file pure.pc.

I'm on Ubuntu and installed Pure using the .deb package as instructed here : https://github.com/agraef/pure-lang/wiki/PureOnDebian

I'm guessing the debian package doesn't contain some build dependencies for the LV2 plugins? Am I basically right but missing something? Or should I do this a completely different way?

**Comment by agraef** [comment]
@interstar I believe that you need to have the development files in the pure-dev package installed, it should contain the requisite pure.pc file.

**Comment by interstar** [comment]
OK. That and I needed to install lv2-dev

cheers
