### ISSUE TITLE
Can turn off JIT?

### ISSUE THREAD

**Issue by uncttao** [agraef/pure-lang#33]
Is there any way to completely prevent JIT compilation and only run Pure programs in interpreter/virtual machine mode?

**Comment by agraef** [comment]
There's no interpreter in Pure, so it's not possible. One might write one, but that won't be easy. I actually [did that](http://q-lang.sf.net/), a long while ago. But interpreted term rewriting is rather slow, compared to JIT-compiled code. Which is the reason why I used a JIT backend for Pure in the first place.
